[project]
name = "usu-llm-class-f26"
version = "0.1.0"
description = "Repository for USU LLM Class DSAI-5810/6810, Fall 2026"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datasets>=5.0.1",
    "marimo>=0.24.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.4",
]

[tool.pytest.ini_options]
addopts = "--cov=src --cov-fail-under=80"
