[project]
name = "usu-llm-class-f26"
version = "0.1.0"
description = "Repository for USU LLM Class DSAI-5810/6810, Fall 2026"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-colab-cli>=0.7.2",
    "modal>=1.5.5",
    "pandas>=3.0.6",
    "prek>=0.5.3",
    "scikit-learn>=1.9.1",
    "truststore>=0.10.4",
    "zenml[local,server]>=0.97.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.4",
]

[tool.pytest.ini_options]
addopts = "--cov=src --cov-fail-under=80"

[tool.uv]
override-dependencies = ["jupyter-kernel-client>=0.9"]
