import csv
import random
import re
from pathlib import Path

ACTION_VERBS = [
    "activate",
    "add",
    "adjust",
    "align",
    "attach",
    "avoid",
    "begin",
    "bolt",
    "calibrate",
    "carry",
    "check",
    "choose",
    "clean",
    "close",
    "collect",
    "connect",
    "cool",
    "cut",
    "deactivate",
    "decelerate",
    "disconnect",
    "disengage",
    "dispose",
    "drain",
    "drop",
    "empty",
    "engage",
    "enter",
    "exit",
    "fasten",
    "fill",
    "fold",
    "grip",
    "guide",
    "heat",
    "hold",
    "inspect",
    "install",
    "isolate",
    "join",
    "lift",
    "load",
    "lock",
    "lower",
    "lubricate",
    "measure",
    "monitor",
    "move",
    "open",
    "operate",
    "place",
    "position",
    "pour",
    "press",
    "pull",
    "push",
    "raise",
    "release",
    "remove",
    "repair",
    "replace",
    "report",
    "reset",
    "rotate",
    "secure",
    "select",
    "separate",
    "shut",
    "slide",
    "start",
    "stop",
    "tighten",
    "transfer",
    "turn",
    "unfasten",
    "unlock",
    "verify",
    "wipe",
    "wrap",
]


ADVERBS = [
    "immediately",
    "carefully",
    "steadily",
    "slowly",
    "quickly",
    "gently",
    "firmly",
    "securely",
    "gradually",
    "evenly",
    "properly",
    "safely",
    "tightly",
    "loosely",
    "fully",
    "partially",
    "repeatedly",
    "manually",
    "directly",
    "smoothly",
    "with care",
    "with caution",
    "with ease",
    "with thought",
    "with power",
    "with force",
]


ADJECTIVES = [
    "adjustable",
    "aligned",
    "attached",
    "bent",
    "blocked",
    "broken",
    "calibrated",
    "charged",
    "clean",
    "clogged",
    "cold",
    "compatible",
    "compressed",
    "connected",
    "corroded",
    "cracked",
    "damaged",
    "deformed",
    "disconnected",
    "dry",
    "engaged",
    "even",
    "exposed",
    "faulty",
    "flexible",
    "free",
    "functional",
    "grounded",
    "guarded",
    "heated",
    "horizontal",
    "inaccessible",
    "inflated",
    "insulated",
    "jammed",
    "loose",
    "lubricated",
    "magnetic",
    "manual",
    "misaligned",
    "missing",
    "mobile",
    "new",
    "noisy",
    "obstructed",
    "open",
    "operational",
    "overheated",
    "oxidized",
    "parallel",
    "powered",
    "pressurized",
    "protected",
    "pulled",
    "pushed",
    "raised",
    "recessed",
    "repaired",
    "replaced",
    "rotating",
    "rusted",
    "safe",
    "sealed",
    "secure",
    "sharp",
    "slack",
    "slippery",
    "smooth",
    "stable",
    "stationary",
    "stiff",
    "straight",
    "switched",
    "tight",
    "tilted",
    "unbalanced",
    "unblocked",
    "unconnected",
    "unlocked",
    "unpowered",
    "unstable",
    "used",
    "vertical",
    "vibrating",
    "visible",
    "worn",
    "wet",
    "widened",
    "wireless",
    "accurate",
    "active",
    "automatic",
    "auxiliary",
    "defective",
    "durable",
    "efficient",
    "empty",
    "external",
    "internal",
    "interlocked",
]


FILLER_PHRASES = [
    "proceed to",
    "go ahead and",
    "don't forget to",
    "it is very important that",
    "please make sure to",
    "you will want to",
    "be sure to",
    "in order to",
    "it is necessary to",
    "at this point, you should",
    "when you are ready,",
    "as needed,",
    "take a moment to",
    "it should be noted that you must",
    "for convenience,",
    "it is imperative that you",
    "it is not essential you",
]

SIMUL_PHRASES = [
    "simultaneously",
    "at the same time,",
    "concurrently",
    "in parallel,",
]

TIMING_PHRASES = [
    "while doing this,",
    "after performing the task,",
    "before moving on,",
    "once the task is complete,",
    "before starting,",
    "after checking the area,",
    "upon completion of Step 1.1.1,",
    "before continuing,",
    "after the previous step,",
    "during the procedure,",
    "during completion",
    "immediately before,",
    "immediately after",
]

NOUNS = [
    "lever",
    "hydraulic cylinder and piston",
    "workbench",
    "gearbox",
    "remote control",
    "torque wrench and socket",
    "servo motor and encoder",
    "battery and charger",
    "caliper and micrometer",
    "pinion and rack",
    "laser level and tripod",
    "bearing puller and slide hammer",
    "sprocket and roller chain",
    "coupling and drive shaft",
    "brake rotor and caliper",
    "linear rail and carriage",
    "safety goggles and gloves",
    "hose and spray nozzle",
    "exhaust manifold and gasket",
    "thread gauge and tap",
    "light switch",
    "extension cord and plug",
    "power cable",
    "pressure gauge and regulator",
    "toolbox and socket set",
    "vise and workpiece",
    "first aid kit and bandages",
    "chain hoist and lifting sling",
    "microphone and speaker",
    "wheel hub and bearing",
    "keyboard and wrist rest",
    "pneumatic cylinder and air valve",
    "filter",
    "belt",
    "chain",
    "clamp",
    "bracket",
    "frame",
    "control panel",
    "cover",
    "guard",
    "access cover",
    "oil reservoir",
    "coolant tank",
    "hydraulic accumulator",
    "junction box",
    "electrical enclosure",
    "parts bin",
    "hand tool",
    "wrench",
    "hammer",
    "screwdriver",
    "pliers",
    "drill",
    "saw",
    "blade",
    "chisel",
    "file",
    "wire brush",
    "deburring cloth",
    "abrasive pad",
    "ladder",
    "parts crate",
    "roller conveyor",
    "tool drawer",
    "machine cabinet",
    "access door",
    "inspection window",
    "mounting plate",
    "gantry crane",
    "guide rail",
    "safety barrier",
    "wire rope",
    "latch",
    "lock",
    "hex key",
    "cotter pin",
    "nameplate",
    "warning placard",
    "gauge",
    "meter",
    "scale",
    "thermocouple",
    "cycle counter",
    "touchscreen controller",
    "motor drive",
    "limit switch and actuator",
    "label printer",
    "flow meter",
    "vibration sensor",
    "fan",
    "compressor",
    "idler pulley",
    "hydraulic fitting",
    "welding torch",
    "drill chuck",
    "vise jaw",
    "impeller",
    "safety interlock",
    "threaded rod",
]

EXTRA_DESCRIPTION = [
    "on the side",
    "in the northeast direction",
    "on the side of the plane",
    "as was instructed previously",
    "as described by a principle engineer",
    "at the marked position",
    "along the upper edge",
    "near the center of the assembly",
    "toward the rear of the machine",
    "away from the moving parts",
    "on the left side of the frame",
    "on the right side of the frame",
    "beneath the mounting bracket",
    "above the control panel",
    "inside the protective enclosure",
    "outside the marked boundary",
    "next to the access panel",
    "between the two support rails",
    "at a right angle to the base",
    "in the clockwise direction",
    "in the counterclockwise direction",
    "toward the front of the work area",
    "facing the operator",
    "with the label facing outward",
    "at the specified depth",
    "to the indicated measurement",
    "within the marked area",
    "without contacting nearby components",
    "clear of the cable path",
    "in line with the reference mark",
    "at the location shown in the diagram",
    "as specified in the service manual",
    "according to the inspection report",
    "as directed by the supervisor",
    "using the approved procedure",
    "in the order shown",
    "with the edges aligned",
    "with the fasteners facing upward",
    "so the connector remains accessible",
    "until it reaches the stop",
    "without changing its orientation",
    "as close as possible to the support",
    "at the designated work station",
    "near the reference point",
    "under the specified operating conditions",
    "with the locking pin fully inserted",
    "in the position shown on the drawing",
]

DEPENDENT_CLAUSES = [
    "providing the proper paperwork",
    "ensuring the team is safe and secure",
    "verifying the work of others",
    "handling the equipment correctly",
    "keeping the work area clear",
    "following the manufacturer's instructions",
    "checking that the power is disconnected",
    "wearing the required protective equipment",
    "using the correct tool for the task",
    "maintaining a firm grip on the handle",
    "confirming that the load is balanced",
    "watching for unexpected movement",
    "keeping hands clear of moving parts",
    "making sure the fasteners are tight",
    "monitoring the pressure gauge",
    "avoiding contact with hot surfaces",
    "supporting the assembly during removal",
    "aligning the components before installation",
    "preventing debris from entering the mechanism",
    "securing loose cables away from the machine",
    "checking the equipment for visible damage",
]

ENDING_FILLER = [
    "in order to proceed",
    "to continue",
    "before going on",
    "after using the product",
    "after displaying",
    "before returning",
    "after returning",
    "when the task is complete",
    "before starting the next step",
    "after the operation is finished",
    "once everything is in place",
    "when you are ready to continue",
    "before proceeding further",
    "after checking the result",
    "to ensure proper operation",
    "for the next procedure",
    "as part of the process",
    "when finished with the task",
]

PERSONAL_NOUNS = [
    "operators",
    "engineers",
    "technicians",
    "mechanics",
    "inspectors",
    "supervisors",
    "assemblers",
    "maintenance workers",
    "trainees",
    "contractors",
]

PERSONAL_ACTIONS = [
    "cannot perform",
    "can perform",
    "are restricted from performing checks",
    "are able to write the instructions",
    "must inspect",
    "should verify",
    "are required to wear protective equipment",
    "are responsible for checking",
    "may operate the machine",
    "should not handle damaged parts",
    "have permission to access the work area",
    "need to report equipment problems",
    "are trained to repair the assembly",
    "are qualified to use the lifting equipment",
    "can safely remove the cover",
    "must not bypass the safety interlock",
    "should communicate any changes",
    "are expected to follow the procedure",
    "can request assistance",
    "must secure the load",
    "should document the inspection",
    "can check the pressure gauge",
    "may adjust the control settings",
    "are prohibited from disconnecting the grounding wire",
    "need to calibrate the instrument",
    "should clean the work surface",
    "can replace worn components",
    "must notify the supervisor",
    "are authorized to start the equipment",
    "cannot access the restricted area",
]

CONJUNCTION_WORDS = ["because", "since", "when", "whenever", "while", "once"]

PHRASE_INPUTS = [
    "<TIMING_PHRASE> <VERB1> the <NOUN1> then <VERB2> the <NOUN2> <EXTRA_DESCRIPTION>.",
    "<VERB1> the <NOUN1> <EXTRA_DESCRIPTION>.",
    "<FILLER_PHRASE> <VERB1> the <NOUN1> <TIMING_PHRASE>",
    "<VERB1> or <VERB2> the <ADJECTIVE1> <NOUN1>.",
    "IF the <NOUN1> is on the <NOUN2>, THEN <VERB1> the <NOUN3> <EXTRA_DESCRIPTION>.",
    "<VERB1> the <ADJECTIVE1> <NOUN1> <EXTRA_DESCRIPTION>, <DEPENDENT_CLAUSE>.",
    "<FILLER_PHRASE> <VERB1> the <NOUN1> <TIMING_PHRASE>:",
    "<FILLER_PHRASE> <VERB1> the <NOUN1> <ENDING_FILLER>.",
    "<VERB1> the <NOUN1> <DEPENDENT_CLAUSE> then <VERB2> the <NOUN2> <TIMING_PHRASE>.",
    "<SIMUL_PHRASE> <VERB1> the <NOUN1> and <VERB2> the <NOUN2>.",
    "IF <PERSONAL_NOUN1> <PERSONAL_ACTION1>, THEN <VERB1> a <NOUN1> <TIMING_PHRASE>.",
    "<FILLER_PHRASE> <VERB1> the <NOUN1> <CONJUNCTION_WORD> the <PERSONAL_NOUN1> <PERSONAL_ACTION1>.",
    "Do not <VERB1> the <NOUN1> <ADVERB1>, <VERB1> it <ADVERB2>.",
    "if the <NOUN1> is/are <ADJECTIVE1>, then <VERB1> the <NOUN1> from each <PERSONAL_NOUN1>.",
    "<FILLER_PHRASE> <VERB1> a <NOUN1> <ENDING_FILLER>.",
    "<FILLER_PHRASE> <VERB1> the <NOUN1> <ADVERB1>.  <TIMING_PHRASE>, <VERB2> a <NOUN2> <ADVERB2>.",
    "<VERB1>, <VERB2>, and <VERB3> the <NOUN1>.",
    "<VERB1> and <VERB2> the <NOUN1>.",
    "<VERB1> the <NOUN1> and <NOUN2> <EXTRA_DESCRIPTION>.",
    "<VERB1> the <NOUN1> <EXTRA_DESCRIPTION>.",
]

PHRASE_OUTPUTS = [
    "<**VERB1**> the <NOUN1> <TIMING_PHRASE>.|<**VERB2**> the <NOUN2> <EXTRA_DESCRIPTION>.",
    "<**VERB1**> the <NOUN1> <EXTRA_DESCRIPTION>.",
    "<**VERB1**> the <NOUN1> <TIMING_PHRASE>.",
    "<**VERB1**> or <**VERB2**> the <ADJECTIVE1> <NOUN1>.",
    "IF the <NOUN1> is on the <NOUN2>, THEN <VERB1> the <NOUN3> <EXTRA_DESCRIPTION>.",
    "<**VERB1**> the <ADJECTIVE1> <NOUN1> <EXTRA_DESCRIPTION>.",
    "<**VERB1**> the <NOUN1> <TIMING_PHRASE>:",
    "<**VERB1**> the <NOUN1> <ENDING_FILLER>.",
    "<**VERB1**> the <NOUN1> <DEPENDENT_CLAUSE>.|<**VERB2**> the <NOUN2> <TIMING_PHRASE>.",
    "<**VERB1**> the <NOUN1> and <**VERB2**> the <NOUN2> <SIMUL_PHRASE>.",
    "IF <PERSONAL_NOUN1> <PERSONAL_ACTION1>, THEN <VERB1> a <NOUN1> <TIMING_PHRASE>.",
    "<**VERB1**> the <NOUN1>.",
    "<**VERB1**> the <NOUN1> <ADVERB2>.",
    "IF the <NOUN1> is/are <ADJECTIVE1>, THEN <VERB1> the <NOUN1> from each <PERSONAL_NOUN1>.",
    "<**VERB1**> a <NOUN1>.",
    "<**VERB1**> the <NOUN1> <ADVERB1>.|<**VERB2**> a <NOUN2> <ADVERB2> <TIMING_PHRASE>.",
    "<**VERB1**> the <NOUN1>.|<**VERB2**> the <NOUN1>.|<**VERB3**> the <NOUN1>.",
    "<**VERB1**> the <NOUN1>.|<**VERB2**> the <NOUN1>.",
    "<**VERB1**> the <NOUN1> and <NOUN2> <EXTRA_DESCRIPTION>.",
    "<**VERB1**> the <NOUN1> <EXTRA_DESCRIPTION>.",
]


def generate_data(n_samples: int = 1000):
    if len(PHRASE_INPUTS) != len(PHRASE_OUTPUTS):
        raise ValueError("PHRASE_INPUTS and PHRASE_OUTPUTS must have matching lengths")

    value_lists = {
        "VERB": ACTION_VERBS,
        "ADVERB": ADVERBS,
        "ADJECTIVE": ADJECTIVES,
        "FILLER_PHRASE": FILLER_PHRASES,
        "SIMUL_PHRASE": SIMUL_PHRASES,
        "TIMING_PHRASE": TIMING_PHRASES,
        "NOUN": NOUNS,
        "EXTRA_DESCRIPTION": EXTRA_DESCRIPTION,
        "DEPENDENT_CLAUSE": DEPENDENT_CLAUSES,
        "ENDING_FILLER": ENDING_FILLER,
        "PERSONAL_NOUN": PERSONAL_NOUNS,
        "PERSONAL_ACTION": PERSONAL_ACTIONS,
        "CONJUNCTION_WORD": CONJUNCTION_WORDS,
    }
    marker_pattern = re.compile(r"<([^<>]+)>")
    token_pattern = re.compile(r"([A-Z_]+?)(\d*)")
    samples = []

    def fill_template(template, substitutions, used_values):
        def replace_marker(match):
            marker = match.group(1)
            is_bold = marker.startswith("**") and marker.endswith("**")
            token = marker[2:-2] if is_bold else marker
            token_match = token_pattern.fullmatch(token)
            if token_match is None:
                return match.group(0)

            category, _index = token_match.groups()
            if category not in value_lists:
                return match.group(0)

            if token not in substitutions:
                options = value_lists[category]
                unused_options = [
                    option for option in options if option not in used_values[category]
                ]
                choices = unused_options or options
                substitutions[token] = random.choice(choices)
                used_values[category].add(substitutions[token])

            value = substitutions[token]
            if is_bold:
                return f"**{value.upper()}**"
            return value

        return marker_pattern.sub(replace_marker, template)

    for _ in range(n_samples):
        phrase_index = random.randrange(len(PHRASE_INPUTS))
        substitutions = {}
        used_values = {category: set() for category in value_lists}

        sample = {
            "in": fill_template(
                PHRASE_INPUTS[phrase_index], substitutions, used_values
            ),
            "out": fill_template(
                PHRASE_OUTPUTS[phrase_index], substitutions, used_values
            ),
        }
        sample["in"] = sample["in"][:1].upper() + sample["in"][1:]
        sample = {
            key: re.sub(r",(?=\s*(?:[.!?]|\||$))", "", value)
            for key, value in sample.items()
        }
        samples.append(sample)

    return samples


if __name__ == "__main__":
    samples = generate_data(n_samples=1000)
    output_path = (
        Path(__file__).resolve().parent.parent / "training_data" / "generate_data.csv"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=["input", "output"])
        writer.writeheader()
        writer.writerows(
            {"input": sample["in"], "output": sample["out"]} for sample in samples
        )
